import { parseCurl } from './curl.js';
import {
  renderConversationHtml, renderIndexHtml, extractFileIds,
  safeFilename, guessExt,
} from './render.js';

const $ = (id) => document.getElementById(id);
const logEl = $('log');
const statusEl = $('status');
const bar = $('bar');

const PROXY_KEY = 'chatgpt-takeout.proxy';
$('proxy').value = localStorage.getItem(PROXY_KEY) || '';
$('proxy').addEventListener('change', () => localStorage.setItem(PROXY_KEY, $('proxy').value.trim()));

function log(msg) {
  logEl.textContent += msg + '\n';
  logEl.scrollTop = logEl.scrollHeight;
}
function setStatus(text, cls = '') {
  statusEl.textContent = text;
  statusEl.className = 'status muted ' + cls;
}
function progress(done, total) {
  if (total > 0) {
    bar.style.display = '';
    bar.max = total;
    bar.value = done;
  } else {
    bar.style.display = 'none';
  }
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

let aborted = false;
let archive = null; // last successful run, kept for download

$('stop').addEventListener('click', () => { aborted = true; });

$('start').addEventListener('click', async () => {
  aborted = false;
  archive = null;
  $('result').style.display = 'none';
  logEl.textContent = '';
  setStatus('Starting…');

  const proxy = $('proxy').value.trim().replace(/\/+$/, '');
  if (!proxy) { setStatus('Set a Proxy URL first.', 'err'); return; }
  let parsed;
  try {
    parsed = parseCurl($('curl').value);
  } catch (e) {
    setStatus('cURL parse error: ' + e.message, 'err');
    return;
  }
  const rate = Math.max(0, parseFloat($('optRate').value) || 0) * 1000;
  const wantAssets = $('optAssets').checked;
  $('start').disabled = true;
  $('stop').disabled = false;
  try {
    archive = await run({ proxy, headers: parsed.headers, rate, wantAssets });
    if (aborted) {
      setStatus('Stopped.', 'err');
    } else {
      setStatus(`Done. ${archive.conversations.length} conversations, ${Object.keys(archive.assets).length} assets.`, 'ok');
      $('result').style.display = '';
      $('preview').onclick = (e) => {
        e.preventDefault();
        openPreview(archive);
      };
    }
  } catch (e) {
    setStatus('Error: ' + (e && e.message || e), 'err');
    log(String(e && e.stack || e));
  } finally {
    $('start').disabled = false;
    $('stop').disabled = true;
  }
});

$('download').addEventListener('click', async () => {
  if (!archive) return;
  setStatus('Building zip…');
  const zip = new JSZip();
  for (const conv of archive.conversations) {
    zip.file(`conversations/${conv.fileName}`, JSON.stringify(conv.data, null, 2));
  }
  zip.file('index.json', JSON.stringify(archive.list, null, 2));
  for (const [fid, blob] of Object.entries(archive.assetBlobs)) {
    zip.file(`assets/${fid}${archive.assetExt[fid]}`, blob);
  }
  // HTML
  const entries = [];
  // Build assets map relative to html/
  const assetsMap = {};
  for (const fid of Object.keys(archive.assetBlobs)) {
    assetsMap[fid] = `../assets/${fid}${archive.assetExt[fid]}`;
  }
  for (const conv of archive.conversations) {
    const html = renderConversationHtml(conv.data, assetsMap);
    const name = `${safeFilename(conv.data.title || 'Untitled')}_${(conv.data.id || '').slice(0, 8)}.html`;
    zip.file(`html/${name}`, html);
    entries.push({
      title: conv.data.title || 'Untitled',
      path: name,
      created: fmtTs(conv.data.create_time),
      updated: fmtTs(conv.data.update_time),
    });
  }
  zip.file('html/index.html', renderIndexHtml(entries));
  zip.file('README.txt', `Generated by chatgpt-takeout
${entries.length} conversations · ${Object.keys(archive.assetBlobs).length} assets
Open html/index.html in any browser.
`);
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' },
    (meta) => setStatus(`Packing… ${meta.percent.toFixed(0)}%`));
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `chatgpt-takeout-${new Date().toISOString().slice(0, 10)}.zip`;
  a.click();
  URL.revokeObjectURL(url);
  setStatus(`Done. ${entries.length} conversations packed.`, 'ok');
});

function fmtTs(ts) {
  if (!ts) return '';
  const d = new Date(ts * 1000);
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

function openPreview(arc) {
  // Open html/index.html in a new tab using blob URLs for assets.
  const assetsMap = {};
  for (const [fid, blob] of Object.entries(arc.assetBlobs)) {
    assetsMap[fid] = URL.createObjectURL(blob);
  }
  // Build a single HTML page that lists all conversations as <details>.
  const docs = arc.conversations.map((c) => {
    const html = renderConversationHtml(c.data, assetsMap);
    return `<details><summary>${escapeHtml(c.data.title || 'Untitled')} <span style="color:#888">${fmtTs(c.data.update_time)}</span></summary>
<iframe srcdoc="${escapeAttr(html)}" style="width:100%;height:80vh;border:1px solid #eee;border-radius:8px;margin:8px 0"></iframe></details>`;
  }).join('');
  const w = window.open();
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Preview</title>
<style>body{font-family:sans-serif;max-width:1000px;margin:0 auto;padding:24px}details{margin:6px 0;border-bottom:1px solid #eee;padding:6px 0}summary{cursor:pointer;font-weight:600}</style>
</head><body><h1>Preview · ${arc.conversations.length} conversations</h1>${docs}</body></html>`);
  w.document.close();
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
function escapeAttr(s) { return escapeHtml(s); }

async function proxiedFetch(proxy, path, headers, init = {}) {
  const url = proxy + (path.startsWith('/') ? path : '/' + path);
  const opts = { ...init, headers: { ...headers, ...(init.headers || {}) } };
  return fetch(url, opts);
}

async function run({ proxy, headers, rate, wantAssets }) {
  // 1) List conversations
  setStatus('Listing conversations…');
  const list = [];
  let offset = 0;
  const limit = 100;
  while (!aborted) {
    const r = await proxiedFetch(proxy, `/backend-api/conversations?offset=${offset}&limit=${limit}&order=updated`, headers);
    if (!r.ok) throw new Error(`list failed: HTTP ${r.status} ${await r.text()}`);
    const data = await r.json();
    const items = data.items || [];
    if (!items.length) break;
    list.push(...items);
    log(`listed ${list.length}`);
    if (items.length < limit) break;
    offset += items.length;
    await sleep(rate);
  }
  if (aborted) return { conversations: [], list, assetBlobs: {}, assetExt: {} };

  // 2) Fetch each conversation
  const conversations = [];
  for (let i = 0; i < list.length; i++) {
    if (aborted) break;
    const c = list[i];
    setStatus(`Downloading conversation ${i + 1}/${list.length}…`);
    progress(i, list.length);
    const r = await proxiedFetch(proxy, `/backend-api/conversation/${c.id}`, headers);
    if (!r.ok) { log(`skip ${c.id}: HTTP ${r.status}`); continue; }
    const data = await r.json();
    const fname = `${safeFilename(data.title || 'Untitled')}_${(data.id || '').slice(0, 8)}.json`;
    conversations.push({ fileName: fname, data });
    if ((i + 1) % 10 === 0) log(`fetched ${i + 1}/${list.length}`);
    await sleep(rate);
  }

  // 3) Assets
  const assetBlobs = {};
  const assetExt = {};
  if (wantAssets && !aborted) {
    const ids = new Set();
    for (const c of conversations) extractFileIds(c.data, ids);
    const arr = [...ids].sort();
    log(`found ${arr.length} file ids`);
    let ok = 0, fail = 0;
    for (let i = 0; i < arr.length; i++) {
      if (aborted) break;
      const fid = arr[i];
      setStatus(`Downloading assets ${i + 1}/${arr.length} (ok=${ok} fail=${fail})…`);
      progress(i, arr.length);
      try {
        const meta = await getFileMeta(proxy, fid, headers);
        if (!meta || !meta.url) { fail++; continue; }
        const fr = await fetch(meta.url);
        if (!fr.ok) { fail++; continue; }
        const ct = fr.headers.get('Content-Type') || '';
        const blob = await fr.blob();
        const ext = guessExt(meta.url, ct, meta.name);
        assetBlobs[fid] = blob;
        assetExt[fid] = ext;
        ok++;
      } catch (e) {
        fail++;
      }
      await sleep(rate * 0.4);
    }
    log(`assets: ok=${ok} fail=${fail}`);
  }

  progress(0, 0);
  return { conversations, list, assetBlobs, assetExt };
}

async function getFileMeta(proxy, fid, headers) {
  for (const path of [`/backend-api/files/${fid}/download`, `/backend-api/files/${fid}`]) {
    try {
      const r = await proxiedFetch(proxy, path, headers);
      if (!r.ok) continue;
      const d = await r.json();
      const url = d.download_url || d.url;
      const name = d.file_name || d.name;
      if (url) return { url, name };
    } catch {}
  }
  return null;
}
